import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './component/Navbar'

import ArtPage from "./component/Artdesign";
import SciencePage from "./component/Science";
import MoneyPage from "./component/Money";
import Travel from "./component/Travel";
import OpinionPage from "./component/Opinion";
import Footer from "./component/Footer";
import Life from "./component/Life";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <SciencePage/>
        <ArtPage/>
        <MoneyPage/>
        <Travel/>
        <OpinionPage/>
        <Life/>  
        <Footer/>
        </body>
    </html>
  );
}
